import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) { 
    return Scaffold(
      appBar: AppBar(
        title: const Text('Privacy Policy'),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: EdgeInsets.symmetric(horizontal: 30.sp),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                'Privacy Policy',
                style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 10),
              const Text(
                'Last updated: September 21, 2024',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 20),
              const Text(
                'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.',
                style: TextStyle(fontSize: 16),
              ),
              const SizedBox(height: 20),
              const Text(
                'We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.',
                style: TextStyle(fontSize: 16),
              ),
              const SizedBox(height: 20),
              _buildSectionTitle('Interpretation and Definitions'),
              _buildSubsectionTitle('Interpretation'),
              const Text(
                'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
                style: TextStyle(fontSize: 16),
              ),
              const SizedBox(height: 20),
              _buildSubsectionTitle('Definitions'),
              _buildBoldText('For the purposes of this Privacy Policy:'),
              _buildDefinitionItem('Account', 'means a unique account created for You to access our Service or parts of our Service.'),
              _buildDefinitionItem('Affiliate', 'means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'),
              _buildDefinitionItem('Application', 'refers to Deal Diligence, the software program provided by the Company.'),
              _buildDefinitionItem('Company', 'referred to as either "the Company", "We", "Us" or "Our" in this Agreement refers to Deal Diligence.'),
              _buildDefinitionItem('Country', 'refers to: Utah, United States.'),
              _buildDefinitionItem('Device', 'means any device that can access the Service such as a computer, a cellphone or a digital tablet.'),
              _buildDefinitionItem('Personal Data', 'is any information that relates to an identified or identifiable individual.'),
              _buildDefinitionItem('Service', 'refers to the Application.'),
              _buildDefinitionItem('Service Provider', 'means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.'),
              _buildDefinitionItem('Usage Data', 'refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).'),
              _buildDefinitionItem('You', 'means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.'),
              const SizedBox(height: 20),
              _buildSectionTitle('Collecting and Using Your Personal Data'),
              _buildSubsectionTitle('Types of Data Collected'),
              _buildSubsectionTitle('Personal Data'),
              const Text(
                'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:',
                style: TextStyle(fontSize: 16),
              ),
              _buildBulletPoint('Email address'),
              _buildBulletPoint('First name and last name'),
              _buildBulletPoint('Phone number'),
              _buildBulletPoint('Address, State, Province, ZIP/Postal code, City'),
              const SizedBox(height: 20),
              _buildSubsectionTitle('Usage Data'),
              const Text(
                'Usage Data is collected automatically when using the Service.',
                style: TextStyle(fontSize: 16),
              ),
              const SizedBox(height: 20),
              // Add more sections as needed by repeating similar patterns
            ],
          ),
        ),
      ),
    );
  }

  // Helper methods for structured text
  Widget _buildSectionTitle(String title) {
    return Text(
      title,
      style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
    );
  }

  Widget _buildSubsectionTitle(String title) {
    return Text(
      title,
      style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
    );
  }

  Widget _buildBoldText(String text) {
    return Text(
      text,
      style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
    );
  }

  Widget _buildDefinitionItem(String term, String definition) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: RichText(
        text: TextSpan(
          text: '$term: ',
          style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.black, fontSize: 16),
          children: [
            TextSpan(
              text: definition,
              style: const TextStyle(fontWeight: FontWeight.normal),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildBulletPoint(String text) {
    return Padding(
      padding: const EdgeInsets.only(left: 20.0, bottom: 4.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text("• ", style: TextStyle(fontSize: 16)),
          Expanded(
            child: Text(
              text,
              style: const TextStyle(fontSize: 16),
            ),
          ),
        ],
      ),
    );
  }
}
